mybatis:
  mapper-locations: "${mybatis_mapper_locations:classpath:com/zhaochuninhefei/webpmjava/db/mapper/*.xml}"

server:
  port: "${server_port:18091}"

spring:
  application:
    name: web-pm-sbt4
  datasource:
    driver-class-name: "${spring_datasource_driver_class_name:com.mysql.cj.jdbc.Driver}"
    hikari:
      auto-commit: "${web_pm_hikari_auto_commit:true}"
      connection-test-query: "${web_pm_hikari_connection_test_query:SELECT 1}"
      connection-timeout: "${web_pm_hikari_connection_timeout:300000}"
      idle-timeout: "${web_pm_hikari_idle_timeout:180000}"
      max-lifetime: "${web_pm_hikari_max_lifetime:1800000}"
      maximum-pool-size: "${web_pm_hikari_maximum_pool_size:100}"
      minimum-idle: "${web_pm_hikari_minimum_idle:5}"
      pool-name: "${web_pm_hikari_pool_name:HikariCP-web-pm-springboot}"
    url: "${spring_datasource_url:jdbc:mysql://localhost:3307/db_web_pm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true}"
    type: "${spring_datasource_type:com.zaxxer.hikari.HikariDataSource}"
    username: "${spring_datasource_username:zhaochun1}"
    password: "${spring_datasource_password:zhaochun@GITHUB}"
  threads:
    virtual:
      enabled: "${spring_threads_virtual_enabled:true}"
logging:
  level:
    root: info
  file:
    path: "${logging_file_path:./logs/web-pm-sbt-vt.log}"